<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\uBeac.Common\uBeac.Common.csproj" />
    <ProjectReference Include="..\uBeac.Configuration\uBeac.Configuration.csproj" />
    <ProjectReference Include="..\uBeac.Repositories.EF\uBeac.Repositories.EF.csproj" />
    <ProjectReference Include="..\uBeac.Services\uBeac.Services.csproj" />
    <ProjectReference Include="..\uBeac.Web.Api.Documentation\uBeac.Web.Api.Documentation.csproj" />
    <ProjectReference Include="..\uBeac.Web.Api\uBeac.Web.Api.csproj" />
  </ItemGroup>

</Project>
