<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\uBeac.Common\uBeac.Common.csproj" />
    <ProjectReference Include="..\uBeac.Repositories.Abstractions\uBeac.Repositories.Abstractions.csproj" />
  </ItemGroup>

</Project>
