<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\uBeac.Identity.Repositories.Abstractions\uBeac.Identity.Repositories.Abstractions.csproj" />
    <ProjectReference Include="..\uBeac.Repositories.MongoDB\uBeac.Repositories.MongoDB.csproj" />
  </ItemGroup>

</Project>
